export async function getTop50SongsAllTime() {
  const songs = [
    { artist: "Taylor Kakkiewakkie", title: "Love Story" },
    { artist: "Ed Sheeran", title: "Shape of You" },
    { artist: "Adele", title: "Hello" },
    { artist: "Billie Eilish", title: "Bad Guy" },
    { artist: "Post Malone", title: "Sunflower" },
    { artist: "Maroon 5", title: "Sugar" },
    { artist: "Drake", title: "God's Plan" },
    { artist: "Lizzo", title: "Truth Hurts" },
    { artist: "Shawn Mendes", title: "Señorita" },
    { artist: "Khalid", title: "Young Dumb & Broke" },
    { artist: "Imagine Dragons", title: "Radioactive" },
    { artist: "Ariana Grande", title: "Thank U, Next" },
    { artist: "Beyoncé", title: "Halo" },
    { artist: "The Weeknd", title: "Blinding Lights" },
    { artist: "Sia", title: "Chandelier" },
    { artist: "John Legend", title: "All of Me" },
    { artist: "Camila Cabello", title: "Havana" },
    { artist: "Justin Bieber", title: "Sorry" },
    { artist: "Eminem", title: "Lose Yourself" },
    { artist: "Dua Lipa", title: "New Rules" },
    { artist: "Coldplay", title: "Fix You" },
    { artist: "Rihanna", title: "Diamonds" },
    { artist: "Sam Smith", title: "Stay With Me" },
    { artist: "Alicia Keys", title: "If I Ain't Got You" },
    { artist: "Lil Nas X", title: "Old Town Road" },
    { artist: "Panic! At The Disco", title: "High Hopes" },
    { artist: "Cardi B", title: "Bodak Yellow" },
    { artist: "Travis Scott", title: "SICKO MODE" },
    { artist: "Katy Perry", title: "Roar" },
    { artist: "Halsey", title: "Without Me" },
    { artist: "The Chainsmokers", title: "Closer" },
    { artist: "Selena Gomez", title: "Lose You to Love Me" },
    { artist: "Twenty One Pilots", title: "Stressed Out" },
    { artist: "Ava Max", title: "Sweet but Psycho" },
    { artist: "Imagine Dragons", title: "Believer" },
    { artist: "Lady Gaga", title: "Shallow" },
    { artist: "OneRepublic", title: "Counting Stars" },
    { artist: "Bruno Mars", title: "Uptown Funk" },
    { artist: "Pink", title: "Just Give Me a Reason" },
    { artist: "Kesha", title: "Tik Tok" },
    { artist: "Kendrick Lamar", title: "HUMBLE." },
    { artist: "Jonas Brothers", title: "Sucker" },
    { artist: "Harry Styles", title: "Watermelon Sugar" },
    { artist: "Zedd", title: "The Middle" },
    { artist: "Ariana Grande", title: "7 Rings" },
    { artist: "Justin Timberlake", title: "Can't Stop the Feeling!" },
  ];

  return songs;
}

export async function getTop50SongsLastMonth() {}
export async function getTop50Songs6Months() {}
