name: Deploy to Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and run services
        run: |
          docker-compose up -d
        working-directory: ./docker-compose.yml
