name: DockerHub Build and Push Backend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "7.0"

      - name: Build Docker image
        working-directory: ./backend/SpottedChartsAPI
        run: docker build . -t ${{ secrets.DOCKER_USERNAME}}/spottedcharts-backend:latest

      - name: Log in to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME}}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME}}/spottedcharts-backend:latest
